apiVersion: v1
kind: ConfigMap
metadata:
  name: data-config
data:
  init.sql: |
    CREATE DATABASE test; 
    USE test;
    CREATE TABLE friends (id INT, name VARCHAR(256), age INT, gender VARCHAR(3));
    INSERT INTO friends VALUES (1, 'Ashutosh', 32, 'm');
    INSERT INTO friends VALUES (2, 'Kimi', 29, 'f');
    INSERT INTO friends VALUES (3, 'Jack', 27, 'm');



