apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-deploy-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deploy-app
  minReplicas: 1
  maxReplicas: 128
  targetCPUUtilizationPercentage: 60